site_name: octopi
repo_url: "https://github.com/chanzuckerberg/octopi"
repo_name: "chanzuckerberg/octopi"
copyright: "2025, Jonathan Schwartz"
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  logo: assets/logo.png
  features:
    - content.code.copy
