[tool.poetry]
name = "model_exploration"
version = "0.0.1"
description = "Model architecture exploration for cryoET particle picking"
authors = ["CZII autonomous 3d particle picking team"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
torch = { version = "^2.0.0", extras = ["cuda118"] }
torchvision = "^0.15.2"
matplotlib = "^3.4.3"
tqdm = "*"
zarr = "*"
copick = "^0.5.6"
#copick-utils = {git = "https://github.com/copick/copick-utils.git", branch = "dev"}
monai-weekly = { version = "*", extras = ["mlflow"] }

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
