[tool.poetry]
name = "model_exploration"
version = "0.0.1"
description = "Model architecture exploration for cryoET particle picking"
authors = ["CZII autonomous 3d particle picking team"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
torch = { url = "https://download.pytorch.org/whl/cu118/torch-2.0.1+cu118-cp38-cp38-linux_x86_64.whl" }
torchvision = { url = "https://download.pytorch.org/whl/cu118/torchvision-0.15.2+cu118-cp38-cp38-linux_x86_64.whl" }
torchinfo = "*"
matplotlib = "*"
tqdm = "*"
zarr = "*"
copick = "^0.5.6"
copick_utils = {git = "https://github.com/copick/copick-utils.git", branch = "main"}
monai-weekly[mlflow] = "*"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
