[tool.poetry]
name = "model_explore"
version = "0.0.1"
description = "Model architecture exploration for cryoET particle picking"
authors = ["CZII autonomous 3d particle picking team"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
matplotlib = "^3.4.3"
tqdm = "4.66.5"
copick = "*"
nibabel = "5.2.1"
mlflow = "2.17.0"
optuna = "4.0.0"
plotly = "*"
kaleido = "*"
ipywidgets = "*"
multiprocess = "*"
python-dotenv = "*"
pytorch-lightning = "2.4.0"
monai-weekly = { version = "1.5.dev2448", allow-prereleases = true }
optuna-integration = { version = "*", extras = ["pytorch_lightning"] }
copick-utils = {git = "https://github.com/copick/copick-utils.git", branch = "main"}
torch = { version = "*", source = "https://download.pytorch.org/whl/cu118", allow-prereleases = true }
seaborn = "*"
pandas = "*"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
black = "^24.8.0"
pre-commit = "^3.8.0"
ruff = "^0.6.4"

[tool.poetry.scripts]
create-targets = "model_explore.entry_points.run_create_targets:cli"
create-shellsubmit = "model_explore.entry_points.run_create_shellsubmit:cli"
download-dataportal = "model_explore.download:cli"
train-model = "model_explore.entry_points.run_train:cli"
train-model-slurm = "model_explore.entry_points.run_create_shellsubmit:train_model_slurm"
model-explore = "model_explore.entry_points.run_optuna:cli"
inference = "model_explore.entry_points.run_segment_predict:cli"
inference-slurm = "model_explore.entry_points.run_create_shellsubmit:inference_slurm"
localize = "model_explore.entry_points.run_localize:cli"
localize-slurm = "model_explore.entry_points.run_create_shellsubmit:localize_slurm"
extract-membrane-picks = "model_explore.entry_points.run_extract_mb_picks:cli"
extract-midpoint-picks = "model_explore.entry_points.run_extract_midpoint:cli"
evaluate = "model_explore.entry_points.run_evaluate:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
