[tool.poetry]
name = "octopus"
version = "0.0.1"
description = "Model architecture exploration for cryoET particle picking"
authors = ["CZII autonomous 3d particle picking team"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
matplotlib = "*"
tqdm = "*"
copick = "*"
nibabel = "*"
mlflow = "2.17.0"
optuna = "4.0.0"
plotly = "*"
pandas = "*"
kaleido = "*"
seaborn = "*"
ipywidgets = "*"
torch-ema = "*"
multiprocess = "*"
python-dotenv = "*"
pytorch-lightning = "2.4.0"
monai-weekly = { version = "1.5.dev2448", allow-prereleases = true }
optuna-integration = { version = "*", extras = ["botorch", "pytorch_lightning"] }
copick-utils = {git = "https://github.com/copick/copick-utils.git", branch = "main"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
black = "^24.8.0"
pre-commit = "^3.8.0"
ruff = "^0.6.4"

[tool.poetry.scripts]
download-dataportal = "octopus.download:cli"
create-targets = "octopus.entry_points.run_create_targets:cli"
train-model = "octopus.entry_points.run_train:cli"
train-model-slurm = "octopus.entry_points.run_create_shellsubmit:train_model_slurm"
model-explore = "octopus.entry_points.run_optuna:cli"
inference = "octopus.entry_points.run_segment_predict:cli"
inference-slurm = "octopus.entry_points.run_create_shellsubmit:inference_slurm"
localize = "octopus.entry_points.run_localize:cli"
localize-slurm = "octopus.entry_points.run_create_shellsubmit:localize_slurm"
extract-membrane-picks = "octopus.entry_points.run_extract_mb_picks:cli"
extract-midpoint-picks = "octopus.entry_points.run_extract_midpoint:cli"
evaluate = "octopus.entry_points.run_evaluate:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
